Development Log                                        -*- org -*-

Wherein we should keep track of pertinent things from other public resources,
such as pull requests, issues, mailing list discussions, etc.

* issues
* pull requests
** github #1 "don't repeat variable" @gabc 04e20e1
*** @nibbula 3738638978
    Thanks! That seems like a good correction. I haven't actually used the
    non-git backends in a long time, and it was hard to even test. I imagine
    it's mostly historical now. Maybe it could be useful again someday if someone
    invents a new DVCS/SCM system.

    Did you actually use it? I use it everyday, but I always use it from my
    shell, where it just runs in the shell. I haven't tested running it as an
    individual program in a long time. Thanks again for the fix!
*** @nibbula merged commit 37d08cf into nibbula:master 3738639624
*** 
* COMMENT MeTaDaTa
creation date: [2018-06-21 23:30:55]
creator: "Nibby Nebbulous" <nibbula@gmail.com>
tags: "pull request" github issues log
